### ISSUE TITLE
Color highlight mentioned user in textarea

### ISSUE THREAD

**Issue by felix2056** [Akryum/vue-mention#7]
Is there a way to change the color of mentioned users inside textarea starting from @

**Comment by Akryum** [comment]
Change the color in your CSS, for example:

```css
.mention-selected {
  background: rgb(192, 250, 153);
}
```
